name: Bug Report
description: Report something that isn't working
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly
      placeholder: When I run agent-session, I see...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `agent-session`
        2. Press Option+S
        3. See error
  - type: input
    id: tmux-version
    attributes:
      label: tmux version
      description: Output of `tmux -V`
      placeholder: "tmux 3.4"
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - WSL2
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error messages
      description: Paste any error output here
      render: shell
